#This program is to do the math to calculate the heat generated by ocupants in a room
import math
 
def get_people_data():
    """Return the number of people in a room based on lables.txt"""
    ocupancy_by_room = [] 
    with open('labels.txt', 'r') as file:
        lines = file.readlines()

        for i, line in enumerate(lines):
            label, latitude, longitude = line.strip().split(',')

        # Remove any single quotes from the label
            label = label.replace("'", "")

        # Increment the contents in parentheses
            count = int(label.split('|')[-1])
            ocupancy_by_room.append = count
    return ocupancy_by_room
   
def calc_BTU_of_Ocupied_room(number_of_people: int, surface_area_ofRoom: float, room_internal_temp: float, room_temp_external: float):
    """
    This function returns the BTU generated by bodies in a room and returns it as a float in BTU/Hour    
    """
    r = 20 #isulation rating of the room
    btu_emitted_loss  = (number_of_people * 341.2) - (surface_area_ofRoom * (room_internal_temp - room_temp_external))/20

    return btu_emitted_loss 

def cacl_HVAC_maintain(number_of_people: int, surface_area_ofRoom: float,  room_temp_external: float, temp_desired: float):
    """Calculates the needed changes to HVAC temp to maintain conditions."""
    r = 20 # insulation property

    temp_change_needed = ((room_temp_external + (number_of_people * 100 * 3.412) / (surface_area_ofRoom / r)) - temp_desired)

    temp_change_needed = (round(temp_change_needed * 10))/10

    return temp_change_needed




