#This program is to do the math to calculate the heat generated by ocupants in a room
import math


 
def get_people_data():
    ocupancy_by_room = [] 
    with open('labels.txt', 'r') as file:
        lines = file.readlines()

        for i, line in enumerate(lines):
            label, latitude, longitude = line.strip().split(',')

        # Remove any single quotes from the label
            label = label.replace("'", "")

        # Increment the contents in parentheses
            count = int(label.split('|')[-1])
            ocupancy_by_room.append = count
    return ocupancy_by_room
   
def calc_BTU_of_Ocupied_room(number_of_people: int, surface_area_ofRoom: float, room_internal_temp: float, room_temp_external: float):
    """
    This function returns the BTU generated by bodies in a room and returns it as a float in BTU/Hour    
    """
    r = 20 #isulation rating of the room
    btu_emitted_loss  = (number_of_people * 341.2) - (surface_area_ofRoom * (room_internal_temp - room_temp_external))/20

    return btu_emitted_loss 




